apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-application
  namespace: sample
  labels:
    app: k8s-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-application
  template:
    metadata:
      labels:
        app: k8s-application
    spec:
      serviceAccountName: sample-sa
      containers:
      - name: k8s-application
        image: ashishk6/kubernetes-application:2.0
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: k8s-application-cm