apiVersion: v1
kind: Service
metadata:
  namespace: sample
  name: k8s-application
spec:
  type: NodePort
  selector:
    app: k8s-application
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001